
```{r eval=FALSE}

library(tidyverse)
library(ggpubr)
library(ggrepel)
library(patchwork)
library(reshape2)
library(viridis)
library(ggrastr)

setwd("/Volumes/GoogleDrive/Shared drives/Bioinfo_SwarupLab/Sam_Dropbox/pipelines/cmcf_iop")

# load celltype color scheme
load('review_data/color_scheme.rda')

# load anndata obs table
cell_meta <- read.csv('review_data/AD_atlas_integrated_processed_meta.csv')

# load scvi DEGs:
deg_df <- read.csv('review_data/scvi_celltype_control_DEGs.csv')

```

Volcano plots:

```{r eval=FALSE}

plot_df <- data.frame()
for(comp in unique(deg_df$comparison)){
  print(comp)
  cur_df <- deg_df %>% subset(comparison == comp)
  cur_df$group <- ifelse(cur_df$bayes_factor > 3 & cur_df$lfc_median > 0, comp, 'other')
  top_genes <- cur_df %>% subset(lfc_median >= 0) %>% top_n(3, wt=bayes_factor) %>% .$X %>% as.character

  cur_df$anno <- ifelse(as.character(cur_df$X) %in% top_genes, as.character(cur_df$X), '')

  plot_df <- rbind(plot_df, cur_df)

}

plot_df <- plot_df %>% subset(!(comparison %in% c('PER/END vs Rest', 'COP vs Rest')))
#plot_df$size <- ifelse(plot_df$group == 'other', 0.25, 0.27)

names(color_scheme_snRNA_celltype) <- c(droplevels(plot_df$comparison) %>% levels, 'other')
color_scheme_snRNA_celltype$other <- 'lightgray'
color_scheme_snRNA_celltype[['OPC vs Rest']] <- '#c57fb2'

p <- plot_df %>%
  ggplot(aes(x=lfc_median, y=log(bayes_factor), color=group)) +
  rasterise(geom_point(alpha=0.5, size=0.2), dpi=800) +
  scale_color_manual(values=unlist(color_scheme_snRNA_celltype)) +
  geom_text_repel(
    aes(label=anno), color='black') +
  ylim(0,3) +
  ylab('ln(Bayes Factor)') +
  xlab('log(Fold Change)') +
  facet_wrap(~comparison, ncol=6) +
  theme_pubr() + theme(legend.position='')

pdf('figures/scvi_volcano.pdf', width=10, height=2)
p
dev.off()


```

plot one module score on the umap:

```{r eval=FALSE}

umap_theme <- theme(
  axis.line=element_blank(),
  axis.text.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks=element_blank(),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  panel.background=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  plot.background=element_blank()
)

plot_df <- cell_meta[order(cell_meta$ASC_score, decreasing=FALSE),]


p <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=ASC_score)) +
  rasterise(geom_point(size=0.1, alpha=0.25), dpi=800) + theme_pubr() +
  scale_color_gradient2(low=scales::muted('blue'), mid='white', high=scales::muted('red'),
       guide = guide_colorbar(barwidth=15, barheight=0.5, ticks=FALSE)
     ) + umap_theme

pdf('figures/umap_ASC_score.pdf', width=6, height=6)
p
dev.off()

plot_df <- cell_meta[order(cell_meta$MG_score, decreasing=FALSE),]
p <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=MG_score)) +
  rasterise(geom_point(size=0.1, alpha=0.25), dpi=800) + theme_pubr() +
  scale_color_gradient2(low=scales::muted('blue'), mid='white', high=scales::muted('red'),
       guide = guide_colorbar(barwidth=15, barheight=0.5, ticks=FALSE)
     ) + umap_theme

pdf('figures/umap_MG_score.pdf', width=6, height=6)
p
dev.off()

plot_df <- cell_meta[order(cell_meta$ODC_score, decreasing=FALSE),]
p <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=ODC_score)) +
  rasterise(geom_point(size=0.1, alpha=0.25), dpi=800) + theme_pubr() +
  scale_color_gradient2(low=scales::muted('blue'), mid='white', high=scales::muted('red'),
       guide = guide_colorbar(barwidth=15, barheight=0.5, ticks=FALSE)
     ) + umap_theme

pdf('figures/umap_ODC_score.pdf', width=6, height=6)
p
dev.off()


plot_df <- cell_meta[order(cell_meta$EX_score, decreasing=FALSE),]
p <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=EX_score)) +
  rasterise(geom_point(size=0.1, alpha=0.25), dpi=800) + theme_pubr() +
  scale_color_gradient2(low=scales::muted('blue'), mid='white', high=scales::muted('red'),
       guide = guide_colorbar(barwidth=15, barheight=0.5, ticks=FALSE)
     ) + umap_theme

pdf('figures/umap_EX_score.pdf', width=6, height=6)
p
dev.off()


plot_df <- cell_meta[order(cell_meta$INH_score, decreasing=FALSE),]
p <- plot_df %>%
  ggplot(aes(x=UMAP_1, y=UMAP_2, color=INH_score)) +
  rasterise(geom_point(size=0.1, alpha=0.25), dpi=800) + theme_pubr() +
  scale_color_gradient2(low=scales::muted('blue'), mid='white', high=scales::muted('red'),
       guide = guide_colorbar(barwidth=15, barheight=0.5, ticks=FALSE)
     ) + umap_theme

pdf('figures/umap_INH_score.pdf', width=6, height=6)
p
dev.off()

```

Plot module scores with braak stage:

```{r eval=FALSE}

plot_df <- cell_meta %>% select(c('braak', 'celltype', 'ASC_score', 'EX_score', 'INH_score', 'MG_score', 'ODC_score', 'OPC_score'))
plot_df <- plot_df[!is.na(plot_df$braak),]


# plot_df <- melt(plot_df, id.vars=c('braak', 'celltype'))
#
# p <- plot_df %>% ggplot(aes(group = braak, y=value)) +
#   geom_boxplot() +
#   facet_grid(celltype~variable) + theme_pubr()
#
#
# pdf('figures/scvi_module_scores.pdf', width=12, height=12)
# p
# dev.off()

load('review_data/color_scheme.rda')


plot_list <- list()
for(ct in c('ASC', 'EX', 'INH', 'MG', 'ODC', 'OPC')){

  print(ct)
  # plot for one cluster:
  plot_df <- cell_meta %>% select(c('braak', 'celltype', 'ASC_score', 'EX_score', 'INH_score', 'MG_score', 'ODC_score', 'OPC_score')) %>%
  subset(celltype == ct)

  plot_df <- plot_df[,c('braak', 'celltype', paste0(ct, '_score'))]
  colnames(plot_df)[3] <- 'value'

  plot_list[[ct]] <- plot_df %>%
    ggplot(aes(x=braak, y=value, color=braak, group=braak, fill=braak)) +
    geom_boxplot(outlier.shape=NA, alpha = 0.5, color='black') +
    rasterise(geom_jitter(size=0.1, alpha=0.5), dpi=800) +
    scale_color_gradientn(colors=rev(magma(256))) +
    #geom_point(aes(x=braak, y=value), size=0) +
    geom_smooth(aes(group=1), method = 'lm', color='black', size=0.75) +
    stat_cor(aes(group=1), p.accuracy = 0.00001, r.accuracy = 0.01, color='black', label.y = 0.9, label.x=0) +
    theme_pubr() + theme(legend.position='') +
    ggtitle(paste0(ct, ' score')) +
    ylab('')


}


pdf('figures/scvi_module_scores_no_legend.pdf', width=15, height=3)
plot_list[[1]] | plot_list[[2]] | plot_list[[3]] | plot_list[[4]] | plot_list[[5]] | plot_list[[6]]

dev.off()

pdf('figures/scvi_module_scores.pdf', width=7, height=7)
plot_list[[1]]
dev.off()

```
